[package]
authors = ["d0iasm"]
name = "toybr"
version = "0.1.0"
edition = "2021"
default-run = "toybr"

[features]
cui = ["dep:net", "dep:ui"]
gui = []
wasabi = []

[[bin]]
name = "toybr"
path = "main/main.rs"
required-features = ["wasabi"]

[[bin]]
name = "toybr_gui"
path = "main/main_gui.rs"
required-features = ["gui"]

[[bin]]
name = "toybr_cui"
test = false
path = "main/main_cui.rs"
required-features = ["cui"]

#[lib]
#name = "core"
#path = "core/lib.rs"
#crate-type = ["staticlib"]
#required-features = []

[dependencies]
toybr_core = { path = "./core"}

net = { path = "./net/std", optional=true }
ui = { path = "./ui/cui", optional=true }

#net = { path = "./net_wasabi", optional=true }
#ui = { path = "./ui_wasabi", optional=true }
