[package]
authors = ["d0iasm"]
name = "toybr"
version = "0.1.0"
edition = "2021"
default-run = "toybr"

[lib]
name = "toybr"
path = "src/lib.rs"

[[bin]]
name = "toybr"
path = "src/main.rs"

[[bin]]
name = "toybr_nostd"
path = "src/main_nostd.rs"
required-features = ["nostd"]

[features]
default = ["gtk4", "gdk4", "gio", "once_cell"]
nostd = []

[dependencies]
gtk4 = { version = "0.4.7", optional = true }
gdk4 = { version = "0.4.7", optional = true }
gio = { version = "0.15.11", optional = true }
once_cell = { version = "1.11.0", optional = true }
dns-lookup = "1.0.8"
