[package]
authors = ["d0iasm"]
name = "gui"
version = "0.1.0"
edition = "2021"

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.43.0"
piston_window = "0.128.0"
renderer = { path = "../renderer"}
