[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "aarch64-apple-darwin"

[lib]
target = "aarch64-apple-darwin"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
