[package]
authors = ["d0iasm"]
name = "ui_wasabi"
version = "0.1.0"
edition = "2021"

[dependencies]
saba_core = { path = "../../core" }
#noli = { git = "https://github.com/hikalium/wasabi.git" }
noli = { path = "../../../../noli" }
