[package]
authors = ["d0iasm"]
name = "toybr"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toybr"
test = false
path = "src/main.rs"

[dependencies]
renderer = { path = "./renderer"}
gui = { path = "./gui"}

[workspace]
members = ["renderer", "gui"]
