[package]
authors = ["d0iasm"]
name = "wasabi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "toybr"
test = false
path = "gui/wasabi/src/main.rs"

[dependencies]
renderer = { path = "../../renderer"}
