name: Test saba

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build CUI
      run: |
        cargo build --features=cui --bin=saba_cui
    - name: Run tests
      run: |
        cd core
        cargo test
